### ISSUE TITLE
Some movies are linking to themoviedb, when in fact they are on IMDB

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/telegram-couchpotato-bot#13]
For example, searching for `matilda` 2 of the movies have a `tt` ID which means they are on IMDB. But they link to themovedb.

**Comment by jayrox** [comment]
Is this still an issue? Your example of searching `Matilda` showed all `tt` IDs but they all linked to IMDb. I'd be willing to look into resolving this issue. When you get a chance can you get an example or show where it breaks down in the process?

**Comment by onedr0p** [comment]
What the heck! I tried this yesterday and 2 of the movies for matilda linked to themoviedb with an incorrect link. Now they aren't... Issue resolved I guess lol
