### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by MrTPN** [onedr0p/telegram-couchpotato-bot#15]
Hi Folks,

Not sure if this is one of those user error things, but upon completing configuration of config.json and starting it up i get the following error message:

/home/telegram-bots/telegram-couchpotato-bot/couchpotato.js:8
class Response {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

My config.json file looks like the following:

{
  "telegram":{
    "botToken": "(redacted)"
  },
  "couchpotato":{
    "hostname": "mediamanager",
    "apiKey": "(redacted)",
    "port": 8080,
    "urlBase": "couhpotato",
    "ssl": false,
    "username": "mediaservice",
    "password": "<redacted>"
  }
}

**Comment by onedr0p** [comment]
This usually has to do with a lower node version. I'll push an update in a bit to fix it.

**Comment by onedr0p** [comment]
Push a fix in the latest commit, please read the changelog and the readme, a few things have changed. I added User Auth.

**Comment by MrTPN** [comment]
All sorted now - Thanks for the insanely fast turn around and the new features :D
