### ISSUE TITLE
Bot not showing available Couchpotato profiles

### ISSUE THREAD

**Issue by pap4** [onedr0p/telegram-couchpotato-bot#17]
When adding a movie, bot finds it, but wont show any options as download profiles.

Tried removing and adding profiles in CP, no help. Any ideas?

(Windows 10, node.js latest stable; Sonarr bot works fine)

> {"level":"info","message":"user: 28289084, message: requested to search for series \"space cowboys\"","timestamp":"2016-01-30T14:07:17.561Z"}
> {"level":"info","message":"user: 28289084, message: choose the movie Space Cowboys - 2000","timestamp":"2016-01-30T14:07:19.053Z"}
> {"level":"info","message":"user: 28289084, message: looking for existing movie","timestamp":"2016-01-30T14:07:19.069Z"}
> {"level":"info","message":"user: 28289084, message: requested to get profile list","timestamp":"2016-01-30T14:07:19.069Z"}

**Comment by onedr0p** [comment]
Try disabling qualities (like cam, telesync) you don't use, there's a big when they are all enabled no profiles get sent.

**Comment by pap4** [comment]
Thanks, that helped!

**Comment by onedr0p** [comment]
I'll return this issue, and fix it when I get time!
