### ISSUE TITLE
Authentication is broken

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/telegram-couchpotato-bot#20]
I got a message from a Redditor:

> Hey! Since yesterday I am using your awesome Telegram Bot. It was easy to set up and works as expected, except of one tiny little detail. The authentication mechanic seems somewhat broken. You can request a movie and even perform admin tasks (/users for example) without authentication. I get the message though, that i need to authenticate or need to be an admin to perform the task. But everything is working nonetheless.
> Sorry for contacting you on this way. Greetings, Markus

**Comment by joshghent** [comment]
Yeah getting the same issue. Seems to always refuse the password I have set in config.json

**Comment by stkubica** [comment]
I can confirm, authentication is still broken. Anybody is able to queue a movie for downloading and perform administration tasks without authentication.
