### ISSUE TITLE
Api length

### ISSUE THREAD

**Issue by chris0101** [onedr0p/telegram-couchpotato-bot#21]
I'm getting an error saying "invalid api length"  I've triple checked my api and it's correct from couchpotato...  Any ideas?

**Comment by onedr0p** [comment]
The API key should be 32 characters in length. I am wondering what length yours is / or if couchpotato dev updated it to be different.

**Comment by chris0101** [comment]
It's 34 I just checked,  that's strange,  I havent changed anything

**Comment by chris0101** [comment]
Anything I can do here?

**Comment by onedr0p** [comment]
You can set the API key in the couch potato settings file. config.ini , make sure you stop couch potato, change it, then start it up again. Sorry for the delay.

**Comment by chris0101** [comment]
thanks for the tip! will give that a go shortly
