### ISSUE TITLE
found 0 profile

### ISSUE THREAD

**Issue by delrio1110** [onedr0p/telegram-couchpotato-bot#23]
it doesnt find anything

**Comment by xoniq** [comment]
I also experienced this issue, and fixed this.
Just found out that when you have never hidden an profile before, this option is not given back to the API. (In this case I can safely assume there are no profiles hidden within CouchPotato.)

If there has been a profile hidden before, and all are shown now, the hide option is visible within the API, forever. My pull request takes care of both situations.
