### ISSUE TITLE
Oh no! {"error":"JSON expected"}

### ISSUE THREAD

**Issue by LandMineHare** [onedr0p/telegram-couchpotato-bot#25]
So, everything was working fine until I don't know when. And suddenly I get this error when querying for ANY movie.

> 2016-06-27T12:34:03.968Z - info: config file found /telegram-couchpotato-bot/lib/../config.json
> 2016-06-27T12:34:03.971Z - info: acl file found /telegram-couchpotato-bot/lib/../acl.json
> 2016-06-27T12:34:04.662Z - info: couchpotato bot sardonisCouchBot initialized
> 2016-06-27T12:34:18.638Z - warn: user: 20714333 message: undefined

I've reinstalled everything, reinstalled the dependencies, nothing seems to help and I'm not sure what to do.

**Comment by gmorchio** [comment]
I have the same issue! I haven't done anything new, just died from one day to another. Is there any way to solve this?

**Comment by gmorchio** [comment]
I solved mine, the problem was I've change the URL base for couchpotato, and I didn't reflect it within config.json. So I modified that file and add the URLBase, then everything went well again.
