### ISSUE TITLE
creating a pid file

### ISSUE THREAD

**Issue by pfmephisto** [onedr0p/telegram-couchpotato-bot#30]
Hey guys,
I'm struggling to get the program to create a pid file, so I can monitor it using monit. 
Is it possible have that integrated? Or is there any other way I can active that?

**Comment by dolohow** [comment]
What would like to monit via pidfie?

**Comment by pfmephisto** [comment]
Back then my intention was to use monit to monitor that the telegram bot was still running propperly and in case it had crashed restart it via systemd.
For identifying programs, monit takes either a pid file or a regular expression. In case of the regular expression that would be 'node' and since I have several programs running through node and they all look the same to monit, only specifying a pid file would work.
But if it's only me then we can close the issue, since I've moved away from CP entirely.
