### ISSUE TITLE
[Request] Mark completed with bot?

### ISSUE THREAD

**Issue by schumi2004** [onedr0p/telegram-couchpotato-bot#31]
Could a option be added to mark a download as completed in CP bot only then it's finished in CP?
Option to give Yes for completed or No to search for other release?

**Comment by jzenoz** [comment]
That functionality should be with CP, bot only adds to CP, it's CP's
responsibility to ensure a proper release is downloaded, no?

**Comment by schumi2004** [comment]
Yeah that's correct but as far as i know a movie only gets removed from wanted list when you mark it complete within CP.
So having the possibility to do this from bot would be nice (you already know the release name downloaded from notification) If bot can handle this i don't need to open CP GUI anymore.
