### ISSUE TITLE
Unable to send message to group

### ISSUE THREAD

**Issue by jfnz** [onedr0p/telegram-couchpotato-bot#33]
I am seeing the following in the logs when trying to send to a group:

`ERROR
[notifications.telegrambot] Could not send notification to TelegramBot (token=xxxxxxxxx). Response: [{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}]`

When I test this using curl with the exact same parameters the message is received by the group:

`media@ubuntu:~$ curl -X POST "https://api.telegram.org/botxxxx/sendMessage" -d "chat_id=-xxxx&text=test"
{"ok":true,"result":{"message_id":6,"from":{"id":xxxx,"is_bot":true,"first_name":"CouchPotato-Notifs","username":"notifd_bot"},"chat":{"id":-xxxx,"title":"Chilstan Media Group","type":"group","all_members_are_administrators":true},"date":xxxx,"text":"test"}}`

When I configure the bot in CouchPotato to send to my userID I receive the test message from the bot using the settings that fail to send to the group. Looks like sending to groups is broken somehow - I just can't work out what. Any ideas?

**Comment by jfnz** [comment]
Just to confirm, the SickRage bot works with the same exact parameters on the same server so I can only assume it's CouchPotato specific

**Comment by dolohow** [comment]
Is this still an issue?  I cannot reproduce it...

**Comment by dolohow** [comment]
What's the alternative btw?

**Comment by jfnz** [comment]
> What's the alternative btw?

I've moved to [Radarr](https://radarr.video/).
